### ISSUE TITLE
Specify the user to authenticate

### ISSUE THREAD

**Issue by tipa** [OneDrive/onedrive-sdk-dotnet-msa-auth-adapter#38]
In my app I want my users to choose the OneDrive account to work with.

- Is there any way to show them a UI where they can select their account?
- Or is there a way for me to authenticate a specific account after the user entered his account details somewhere else in my app?

Currently, the account the user is signed in on the device is used without an option to change it. I already googled that issue and looked though the issues here and on the onedrive-sdk-repo, without success

**Comment by daboxu** [comment]
reference: https://github.com/OneDrive/onedrive-sdk-csharp/issues/216
