### ISSUE TITLE
Unable to find package 'Microsoft.OneDrive.Sdk.Authentication'

### ISSUE THREAD

**Issue by ponarunkumar** [OneDrive/onedrive-sdk-dotnet-msa-auth-adapter#4]
![image](https://cloud.githubusercontent.com/assets/6130502/17718627/deee36f0-63e2-11e6-9675-af4cd93129a3.png)

**Comment by mbrewerton** [comment]
I believe you need to be installing Microsoft.OneDriveSDK.Authentication. you are trying to install Microsoft.OneDrive.Sdk.Authentication.
