### ISSUE TITLE
Develop OneDrive desktop Client using c#

### ISSUE THREAD

**Issue by Srusti-Thakkar** [OneDrive/onedrive-sdk-dotnet-msa-auth-adapter#49]
Hello, I want to develop a client just like OneDrive Desktop Client.

I have created Web Application. In that I have used OneDrive Rest API to perform basic operations. Now I want to develop a desktop client and perform same action just like OneDrive Desktop Client do. 

How can I start to develop a client? What are the initial task when fist time linking local folder with OneDrive and how to sync data on regular basis?

Thank you

**Comment by daboxu** [comment]
hi @Srusti-Thakkar sorry I cannot provide support for your client project here, I would say try search for how to build a OneDrive/Dropbox/Google Drive client and search for 3rd party clients on Github. It really depends on your platform. If you want Window 10 platform for example, you probably want to learn the UWP stack and how the FileManager works on that. It is really an open questions and it is up to you to decide your choice. I am glad you want to get involved in OneDrive envrionment and let me know if you got questions about OneDrive APIs/SDKs. FYI, I recommend you starts with [Microsoft Graph API/SDK](https://developer.microsoft.com/en-us/graph/).
