### ISSUE TITLE
Cannot compile for UWP Mobile

### ISSUE THREAD

**Issue by tipa** [OneDrive/onedrive-sdk-dotnet-msa-auth-adapter#5]
When trying to compile a UWP app referencing this library for a phone with the Windows 10 Anniversary Update (therefore ARM architecture), the  following error is raised:

> There was a mismatch between the processor architecture of the project being built "ARM" and the processor architecture of the reference "C:\Users\timop\.nuget\packages\Microsoft.OneDriveSDK.Authentication\1.0.0\lib\win81\Microsoft.OneDrive.Sdk.Authentication.WinRT.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Comment by cdmayer** [comment]
Thanks for reporting. This was an issue with the build process. Going to rebuild, resign binaries, and publish to Nuget. I'll close the issue when done.

**Comment by cdmayer** [comment]
I have uploaded a new version of the package to Nuget: https://www.nuget.org/packages/Microsoft.OneDriveSDK.Authentication/1.0.1

Please try it and let me know if it works. If it does, please close the issue too. Thanks!

**Comment by tipa** [comment]
works now, thanks!
