### ISSUE TITLE
Missing classes under Windows Phone 8.1?

### ISSUE THREAD

**Issue by queequac** [OneDrive/onedrive-sdk-dotnet-msa-auth-adapter#63]
While everything is working as expected (and described here) under UWP, the Nuget package for Windows Phone 8.1 seems to be incomplete. There is no MsaAuthenticationProvider or OnlineIdAuthenticationProvider, just the CredentialCache, CredentialVault, etc.

Has anyone tried this recently under Windows Phone 8.1?

**Comment by ooikengsiang** [comment]
It is one year late, but I encounter the same problem.
Do you find any quick workaround?

**Comment by queequac** [comment]
Nope, in the end I did not add the OneDrive feature to my app's WP81 package.

With the upcoming closing of the wp81 store this is probably nothing to be fixed anymore anyway.

**Comment by ooikengsiang** [comment]
I tried to implement the IAuthenticationProvider with the source code in the repo but WebAuthenticationBroker doesn't seem to have any implementation for Windows Phone 8.1.
Seem like too much work for an obsolete platform.
